name: alz_play
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

  shared_preferences: ^2.2.2



  file_picker: ^8.0.0
  intl: ^0.19.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/background_music.mp3
    - assets/images/happy.png
    - assets/images/neutral.png
    - assets/images/sad.png
    - assets/images/Celrc.png
    - assets/level1/
    - assets/level2/
    - assets/level3/
    - assets/level4/
    - assets/level5/
    - assets/level6/
    - assets/level7/
    - assets/level8/
    - assets/folder1/
    - assets/folder2/
    - assets/folder3/
    - assets/folder4/
    - assets/raccoon.png
    - assets/dog/
    - assets/house/
    - assets/folder1/
    - assets/folder2/
    - assets/trophy/
    - assets/coins/
    - assets/match_game/


